package ch.claudedy.chess.basis;

public enum MoveFeedBack {
    RUNNING, NO_PIECE_SELECTED, PIECE_BLOCKED, ENNEMY_PIECE_SELECTED, CANT_EAT_ENEMY_KING, PIECE_ILLEGAL_MOVE, PIECE_CANT_EAT_ALLY_PIECE, CHECKMATED, STALEMATED, RULES_50;
}
